import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { atomicWrite } from "../vault/atomicWrite.js";
import {
  renderBucketSection,
  renderMemoryHeadlines,
  renderStatsLine,
} from "./render.js";
import type { SkillBundle } from "./types.js";

/**
 * Claude skill bundle layout:
 *
 *   <output>/
 *   ├── SKILL.md                  (entry; YAML frontmatter required)
 *   ├── description.yaml          (skill manifest; matches Anthropic schema)
 *   └── references/
 *       ├── decisions.md
 *       ├── learnings.md
 *       ├── observations.md
 *       ├── entities.md
 *       ├── questions.md
 *       ├── todos.md
 *       └── summaries.md
 *
 * SKILL.md links into references/ via relative paths so agents that
 * support partial-load (Claude Code, Claude.ai) read references on
 * demand instead of pinning the whole bundle in context.
 */
export function writeClaudeBundle(
  bundle: SkillBundle,
  outputDir: string
): string[] {
  mkdirSync(outputDir, { recursive: true });
  mkdirSync(join(outputDir, "references"), { recursive: true });

  const filesWritten: string[] = [];

  const skillMd = renderSkillMd(bundle);
  const skillPath = join(outputDir, "SKILL.md");
  atomicWrite(skillPath, skillMd);
  filesWritten.push(skillPath);

  const descYaml = renderDescriptionYaml(bundle);
  const descPath = join(outputDir, "description.yaml");
  atomicWrite(descPath, descYaml);
  filesWritten.push(descPath);

  const refMap: Array<[string, ReturnType<typeof renderBucketSection>]> = [
    ["decisions.md", renderBucketSection("decisions", bundle.decisions)],
    ["learnings.md", renderBucketSection("learnings", bundle.learnings)],
    ["observations.md", renderBucketSection("observations", bundle.observations)],
    ["entities.md", renderBucketSection("entities", bundle.entities)],
    ["questions.md", renderBucketSection("questions", bundle.questions)],
    ["todos.md", renderBucketSection("todos", bundle.todos)],
    ["summaries.md", renderBucketSection("summaries", bundle.summaries)],
  ];

  for (const [fname, content] of refMap) {
    if (!content) continue;
    const p = join(outputDir, "references", fname);
    atomicWrite(p, content);
    filesWritten.push(p);
  }

  return filesWritten;
}

function renderSkillMd(bundle: SkillBundle): string {
  const stats = renderStatsLine(bundle);
  const name = `vault-mem-${bundle.project}`;
  const description = `Project memory for "${bundle.project}" exported from vault-mem — ${stats}. Read the references/ files for full context before acting on anything ${bundle.project}-related.`;

  return `---
name: ${name}
description: ${jsonEscape(description)}
---

# Vault-mem memory for \`${bundle.project}\`

Generated by \`vault-mem-mcp export-skill\` from the team's vault. This
skill loads the typed, durable memory the team has accumulated for the
\`${bundle.project}\` project: ${stats}.

**When to use:** whenever you're about to make a non-trivial choice
related to \`${bundle.project}\`, open the relevant \`references/\`
file first. The memories are sorted newest-first within each bucket
and include id, confidence, agent, tags, and the full body content.

## What's in this bundle

${tocLine(bundle.decisions.length, "decisions.md", "Decisions made by the team")}
${tocLine(bundle.learnings.length, "learnings.md", "Lessons learned (generalizable patterns)")}
${tocLine(bundle.observations.length, "observations.md", "Facts and findings worth remembering")}
${tocLine(bundle.entities.length, "entities.md", "People, tools, and systems")}
${tocLine(bundle.questions.length, "questions.md", "Open questions awaiting resolution")}
${tocLine(bundle.todos.length, "todos.md", "Action items")}
${tocLine(bundle.summaries.length, "summaries.md", "Rollup summaries (auto-generated)")}

## Most recent decisions

${renderMemoryHeadlines(bundle.decisions, 5)}

## Most recent learnings

${renderMemoryHeadlines(bundle.learnings, 5)}

## Open questions

${renderMemoryHeadlines(bundle.questions, 5)}

---

_Exported from vault-mem at ${bundle.generatedAt}. Memory ids match
the OSS frontmatter pattern \`mem_YYYY-MM-DD_xxxxxx\` so you can
cross-reference them in the source vault if you have access._
`;
}

function tocLine(count: number, filename: string, label: string): string {
  if (count === 0) return `- _no ${label.toLowerCase()} yet_`;
  return `- [\`references/${filename}\`](./references/${filename}) — ${label} (${count})`;
}

function renderDescriptionYaml(bundle: SkillBundle): string {
  // Minimal manifest; expand once we know what each target runtime expects.
  return `# Auto-generated by vault-mem-mcp export-skill.
# Do not edit by hand — re-run \`vault-mem-mcp export-skill ${bundle.project} --target=claude\`.
name: vault-mem-${bundle.project}
version: "0.1.0"
description: |
  Project memory for "${bundle.project}" exported from vault-mem.
  ${renderStatsLine(bundle)}.
entrypoint: SKILL.md
references:
  - references/decisions.md
  - references/learnings.md
  - references/observations.md
  - references/entities.md
  - references/questions.md
  - references/todos.md
  - references/summaries.md
generated_by: vault-mem-mcp
generated_at: "${bundle.generatedAt}"
project: ${bundle.project}
memory_count: ${bundle.stats.total}
`;
}

function jsonEscape(s: string): string {
  // YAML scalar — escape only inner double quotes; wrap in double quotes
  // so colons/quotes inside the description don't trip the YAML parser.
  return JSON.stringify(s);
}
